### ISSUE TITLE
no access rights to submodules

### ISSUE THREAD

**Issue by transfluxus** [jsalt18-sentence-repl/jiant#412]
for both proposed ways of cloning the submodules the error shows up:

```
Cloning into 'jiant'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Iwontbecreative** [comment]
I ran into this issue as well. This is because the repo is configured for pulling submodules using ssh keys but you're likely using https. One way to fix this is to use ssh keys.

See here: https://stackoverflow.com/questions/25957125/git-submodule-permission-denied

You should have access to the submodules are they are all public.

**Comment by transfluxus** [comment]
ahh, indeed, I didn't had a key yet.
then it worked.
I went to the src folder and cloned the clove repo there...

still I think  `.gitmodule` could be writen differently so it's not required
