### ISSUE TITLE
Update to PyTorch v1.0 and AllenNLP 0.8

### ISSUE THREAD

**Issue by W4ngatang** [jsalt18-sentence-repl/jiant#442]
New PyTorch version is out, evidently with big speed ups. Would be good to switch to (as well as possibly updating AllenNLP version).

**Comment by iftenney** [comment]
This seems like a great project for the new SWE :)

**Comment by sleepinyourhat** [comment]
Updated the title: AllenNLP now supports PyTorch 1.0, and we'll presumably have to upgrade both at once.

**Comment by pruksmhc** [comment]
Have gone through the release docs and have a few thoughts on what I'm implementing now. 

@iftenney @sleepinyourhat 
-AllenNLP does have a TrainerBase class (below) but it's possible to not use it, and since the places where trainer.py  should be refactorized is not something that inheriting from TrainerBase class would help,, I think we should not worry about making our SamplingTaskTrainer inherit from this class. 
https://github.com/allenai/allennlp/blob/e08ade81ff6684869883ce3da66941b9d3a37503/allennlp/training/trainer_base.py 
-There's no need to implement from_params if you inherit from torch.Model if the from_param is a simple 1-1 mapping from JSON to the model.

**Comment by pruksmhc** [comment]
So actually there might not be that many changes in terms of upgrading/using some new developments from more recent AllenNLP releases to our code.

**Comment by sleepinyourhat** [comment]
Sounds good to me.

**Comment by W4ngatang** [comment]
SGTM

Is it worth using their BERT implementation over ours? Or is it close enough that it's not worth the extra effort?

**Comment by pruksmhc** [comment]
I think it's close enough that we can just stick to ours.
